.\" Copyright (C) 2002 by Martin Loschwitz
.TH XFCE4_SETUP "1" "November 2002" "xfce4_setup 0.1" "User Commands"
.SH NAME
xfce4_setup \- creates local .xinitrc file for the user who calls the script
.SH SYNOPSIS
.B xfce4_setup
.SH DESCRIPTION
.PP
Creates local .xinitrc file for the user who calls the script. This file 
will make the user able to use Xfce4 by just tiping "startx".
.SH AUTHOR
Written by Martin Loschwitz
.SH "REPORTING BUGS"
Report bugs to <madkiss@madkiss.org>.
.SH COPYRIGHT
Copyright \(co 2002 Martin Loschwitz
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
